// export const MESHBLU_HOST       = 'meshblu.octoblu.dev'
// export const OAUTH_CLIENT_ID    = '5f58b3c1-ac2a-408e-b4ab-d457a135e6d7'
// export const OAUTH_PROVIDER_URI = 'https://oauth.octoblu.dev'
// export const OCTOBLU_URL        = 'https://app.octoblu.dev'
// export const OCTOBLU_API_URL    = 'https://api.octoblu.dev'
// export const OCTOBLU_LOGO_URL   = '//d2zw6j512x6z0x.cloudfront.net/master/d48dc0bf063ecc1477d1163831ee8ff17efbbfae/assets/images/octoblu_logo.png'

export const MESHBLU_HOST       = 'meshblu.octoblu.com'
export const OAUTH_CLIENT_ID    = '0ce978f8-aaf4-4c83-a4d9-162ff35ecb7f'
export const OAUTH_PROVIDER_URI = 'https://oauth.octoblu.com'
export const OCTOBLU_URL        = 'https://app.octoblu.com'
export const OCTOBLU_API_URL    = 'https://api.octoblu.com'
export const OCTOBLU_LOGO_URL   = '//d2zw6j512x6z0x.cloudfront.net/master/d48dc0bf063ecc1477d1163831ee8ff17efbbfae/assets/images/octoblu_logo.png'
